### ISSUE TITLE
why all the code forked from theother project?

### ISSUE THREAD

**Issue by PmuYi** [hybridnetwork/hxd#6]
![image](https://user-images.githubusercontent.com/22147594/38158686-fc53b9ac-34cb-11e8-911d-cc9dae38b1c0.png)

**Comment by bogrod** [comment]
That is how open source works. It doesn't make sense to re-invent the wheel each time. This allows us to focus on creating new innovations like quantum resistant signature schemes instead of re-writing rpc calls. We are grateful to the contributors from other projects like Decred and Bitcoin that have provided foundations for us to continue to build from. Without forking existing code the entire community would be slow to progress.
