### ISSUE TITLE
Using decred chain on HXD node

### ISSUE THREAD

**Issue by mcb345** [hybridnetwork/hxd#9]
Is it possible to use decred chain on HXD node ? as its hard forked from decred...
if its a yes, how to achieve that ? --datadir bitcoind equivalent ?

**Comment by bogrod** [comment]
This is not possible because the way the messages are encoded are unique to each network. That means that if a decred node tries to send a message to an hxd node it will be rejected because the decred node will parse the message for some bytes to indicate if the message is intended for the decred network.

**Comment by mcb345** [comment]
@bogrod I tried running hxd on mainnet, without any "--testnet" flag, but I am not sure why it isnt downloading any block , do you have any idea ?

**Comment by bogrod** [comment]
@mcb345 this is because there is no network running this software currently with blocks. This means that with or without --testnet flag your node will not be able to find any blocks. Currently the only way to test the software yourself is to use the `--simnet` flag when running. This will create a local simulated network you can test.
